### ISSUE TITLE
Integrate Tilwind and Define Project Structure

### ISSUE THREAD

**Issue by Zino0031** [202306-NEA-DZ-FEW/team-five#20]
**Task title**
Integrate Tilwind and Define Project Structure

**Task description**
This issue is focused on integrating Tilwind into our project and defining the project structure for improved development efficiency and maintainability.

**Subtasks**
- [x] Integrate Tilwind CSS framework
- [x] Define the project folder structure

**Comment by melissasidisid** [comment]
DONE
